site_name: x509-limbo
site_url: https://trailofbits.github.io/x509-limbo/
docs_dir: site
site_dir: site_html
plugins:
  - gen-files:
      scripts:
        - site/render-testcases.py
markdown_extensions:
  # Makes sure we render `<https://...>`-style links correctly.
  - pymdownx.magiclink
