name: run harnesses
description: Run x509-limbo's in-repo harnesses and cache their results
outputs:
  cache-hit:
    description: "Whether or not the cache was hit"
    value: "${{ steps.restore-cache.outputs.cache-hit }}"

runs:
  using: composite

  steps:
    # This action assumes that actions/checkout has run, leaving limbo.json
    # in place for the cache check.

    - uses: actions/cache/restore@v4
      id: restore-cache
      with:
        # TODO: Fix the cache key here.
        key: limbo-harness-results-${{ hashFiles('limbo.json') }}
        path: results

    - uses: actions/setup-python@v5
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        python-version: ">=3.12"
        cache: "pip"
        cache-dependency-path: pyproject.toml

    - uses: actions/setup-go@v5
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        go-version: ">=1.20.5"

    - name: setup limbo
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: make dev

    - name: run harnesses
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: make test -j

    - uses: actions/cache/save@v4
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        key: limbo-harness-results-${{ hashFiles('limbo.json') }}
        path: results
