name: Label checks

on:
  pull_request:
    types:
      - labeled

jobs:
  label-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Check regression labels
      if: |
        !(
          contains(github.event.pull_request.labels.*.name, ':see_no_evil: no-regressions') ||
          (
            contains(github.event.pull_request.labels.*.name, ':skull: regressions') &&
            contains(github.event.pull_request.labels.*.name, 'regressions-triaged')
          )
        )
      run: |
        echo "Label conditions not met: there are untriaged regressions."
        exit 1
