name: Testcase regression detection

on:
  pull_request:

jobs:
  regressions:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true

      - uses: ./.github/actions/run-harnesses
        id: run-harnesses

      - name: run regression detection
        run: make run ARGS="regression --detect-only --output regression-data.json"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: upload regression artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: regression-data
          path: regression-data.json
          retention-days: 7
