name: test-harness

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-gocryptox509:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.5"

      - name: run tests
        run: make test-go
