name: test-harness

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gocryptox509:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ">=3.12"

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.5"

      - name: run tests
        run: make test-go

      - name: render summary
        run: |
          python ./harness/render-summary.py \
            limbo.json \
            harness/gocryptox509/results.json
  openssl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ">=3.12"

      - name: run tests
        run: make CXX=clang++ test-openssl

      - name: render summary
        run: |
          python ./harness/render-summary.py \
            limbo.json \
            harness/openssl/results.json
